import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import shopify from 'vite-plugin-shopify'
import shopifyClean from '@driver-digital/vite-plugin-shopify-clean'
import tailwindcss from '@tailwindcss/vite'

/*
For some reason, when terminating or swapping branches early
The tunnel feature bugs out and breaks the preview theme.
*/
const shopifyConfig = {
  // tunnel: true
}

/**
 * Generates snippets/island-preload.liquid from the Vite manifest after each
 * build: a case statement mapping island tag names to <link rel="modulepreload">
 * tags for the island's chunk and its shared-chunk imports. Layouts render it
 * for islands that are critical on the current template, so the browser warms
 * those module fetches instead of waiting for the hydration directive.
 */
function islandPreloadSnippet() {
  let isBuild = false
  return {
    name: 'island-preload-snippet',
    configResolved(config) {
      isBuild = config.command === 'build'
    },
    // In dev the Vite server owns module loading (and the clean plugin
    // removes built assets), so the snippet must go inert — build-time
    // hashed references would 404 against the dev theme.
    configureServer() {
      writeFileSync(
        resolve('snippets/island-preload.liquid'),
        '{% # AUTO-GENERATED by the islandPreloadSnippet plugin in vite.config.js — do not edit. Empty in dev; vite build fills in modulepreload links per island. %}\n'
      )
    },
    closeBundle() {
      if (!isBuild) return
      let manifest
      try {
        manifest = JSON.parse(
          readFileSync(resolve('assets/.vite/manifest.json'), 'utf8')
        )
      } catch {
        return
      }

      const cases = []
      for (const [key, entry] of Object.entries(manifest)) {
        const match = key.match(/^frontend\/islands\/([\w-]+)\.ts$/)
        if (!match) continue

        const files = [entry.file]
        for (const imported of entry.imports ?? []) {
          // Shared chunks only — the theme entrypoint is always loaded.
          if (imported.includes('entrypoints/')) continue
          const dep = manifest[imported]
          if (dep) files.push(dep.file)
        }

        cases.push(`  {%- when '${match[1]}' -%}`)
        for (const file of files) {
          cases.push(
            `    <link rel="modulepreload" href="{{ '${file}' | asset_url }}" crossorigin>`
          )
        }
      }

      const content = [
        "{% # AUTO-GENERATED by the islandPreloadSnippet plugin in vite.config.js on every build — do not edit. Emits modulepreload links for an island's chunk and its shared imports. Usage: {% render 'island-preload', island: 'product-form' %} %}",
        '{%- case island -%}',
        ...cases,
        '{%- endcase -%}'
      ].join('\n')

      writeFileSync(resolve('snippets/island-preload.liquid'), content + '\n')
    }
  }
}

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    shopifyClean(),
    shopify(shopifyConfig),
    tailwindcss(),
    islandPreloadSnippet()
  ],
  build: {
    emptyOutDir: false,
    // Warn if any chunk grows past 250 kB raw. Set just above the lazily
    // loaded Sentry SDK chunk (~220 kB, never on the critical path) so the
    // warning stays meaningful — every other chunk in this theme is < 15 kB.
    chunkSizeWarningLimit: 250,
    // 'hidden' emits .map files without the sourceMappingURL comment, so
    // they're available for Sentry upload but not discoverable by visitors.
    // Maps are excluded from theme push (.shopifyignore) and git (.gitignore).
    sourcemap: 'hidden',
    rollupOptions: {
      output: {
        entryFileNames: '[name].[hash].min.js',
        chunkFileNames: '[name].[hash].min.js',
        assetFileNames: '[name].[hash].min[extname]'
      }
    }
  }
})
